version: '2'
syncs:
  ${SYNC_NAME}-docker-sync:
    src: './'
    sync_userid: 33
    sync_host_ip: '127.0.0.1'
    notify_terminal: true
    sync_excludes_type: 'Name'
    sync_excludes:
      - docs
      - tests
      - build
      - docker
      - reports
      - README.md
      - .env
      - .git
      - .idea
      - .project-x
      - .probo.yml
      - .travis.yml
      - .docker-sync
      - project-x.yml
      - docker-sync.yml
      - docker-compose.yml
      - docker-compose-dev.yml
