language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./bin/phpcs -n --standard=PSR2 ./src
  - ./bin/phpunit --configuration phpunit.xml.dist
