# Reference the database file uploaded to probo's /assets

image: proboci/ubuntu-14.04-lamp:5.6-beta

steps:
  - name: Install composer packages
    plugin: Script
    script:
      - cd $SRC_DIR
      - composer self-update
      - composer install

  - name: Setup Probo environment
    plugin: Script
    script:
      - ln -s $SRC_DIR/docroot /var/www/html
      - chmod -R 775 $SRC_DIR/docroot
      - chown -R www-data:www-data $SRC_DIR/docroot
