sudo: required
language: php

# Run test against these PHP versions.
php:
  - '7.1'

# Enable docker to build out environment.
services:
  - docker

# Catch APT and composer between builds.
cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"

before_install:

  # Disable Xdebug.
  - phpenv config-rm xdebug.ini
  - sudo apt-get update > /dev/null

install:

  # Install composer dependencies.
  - composer install

before_script:

  # Add project composer vendor/bin to $PATH.
  - PWD=$(pwd); export PATH="$PWD/vendor/bin:$PATH"

  # Stop MySQL from running on host, due to docker conflicts.
  - sudo /etc/init.d/mysql stop

  # Start up the project docker services.
  - docker-compose -f docker-compose.yml up -d
  - docker ps

script:

  # Run project level code sniffer.
  # - vendor/bin/phpcs -n

  # Run project level PHPUnit tests.
  # - vendor/bin/phpunit

  # Run project level Behat tests.
  # - vendor/bin/behat -c tests/Behat/behat.yml

# addons:
#   # Add hostname to /ets/hosts file.
#   hosts:
#     - local.example.com
