version: "2"
services:
  nginx:
    image: nginx:latest
    links:
      - php
      - mysql
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: docker/php-fpm
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/99-php-overrides.ini
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/mysql-overrides.cnf:/etc/mysql/mysql.conf.d/99-mysql-overrides.cnf
volumes:
  mysql-data:
    driver: local
