# Reference the database file uploaded to probo's /assets

image: proboci/ubuntu-14.04-lamp:5.6-beta

steps:
  - name: Install composer packages
    plugin: Script
    script:
      - cd $SRC_DIR
      - composer self-update
      - composer install

  - name: Setup Drupal local setup
    plugin: Script
    script:
      - $SRC_DIR/vendor/bin/project-x drupal:local-setup --db-user=root --db-pass=strongpassword --no-interaction --no-docker --no-engine --no-browser

  - name: Setup Probo environment
    plugin: Script
    script:
      - ln -s $SRC_DIR{PROJECT_ROOT} /var/www/html
      - chmod -R 775 $SRC_DIR{PROJECT_ROOT}
      - chown -R www-data:www-data $SRC_DIR{PROJECT_ROOT}
